// Codex CLI adapter.
//
// Instead of driving the Responses API loop ourselves, we shell out to the
// official `codex` binary. It already knows how to: read the vault,
// plan long tasks, edit files, respect CLAUDE.md, stream reasoning to
// stdout, and stop cleanly. We just hand it a task and capture its output.
//
// The CLI reads OPENAI_API_KEY + a provider config.  We write a minimal
// config.toml into CODEX_HOME pointing at our own proxy so the user's
// global ~/.codex/config.toml stays untouched.  The proxy forwards to
// zenn.engineering while charging credits server-side.

import { spawn, type ChildProcess } from 'node:child_process';
import fs from 'node:fs/promises';
import path from 'node:path';
import { VAULT_ROOT, type Config } from './paths.js';

export interface CodexResult {
  stdout: string;
  stderr: string;
  exitCode: number;
  durationMs: number;
}

export class CodexNotInstalled extends Error {
  constructor() {
    super('codex binary not found in PATH — install https://github.com/openai/codex or brew install codex');
  }
}

async function ensureCodexConfig(config: Config): Promise<string> {
  const home = path.join(VAULT_ROOT, '.bm', 'codex');
  await fs.mkdir(home, { recursive: true });
  const cfg = [
    `model = "${config.default_model}"`,
    `model_provider = "bm"`,
    ``,
    `# Auto-generated by Black Magic.  Do not edit; changes will be overwritten.`,
    `[model_providers.bm]`,
    `name = "Black Magic"`,
    `base_url = "${config.zenn_base_url}"`,
    `env_key = "OPENAI_API_KEY"   # codex reads the bearer token from this env var`,
    `wire_api = "responses"`,
    ``,
    `[tools]`,
    `web_search = false   # our own web_search MCP / tool is authoritative`,
    ``,
  ].join('\n');
  await fs.writeFile(path.join(home, 'config.toml'), cfg, 'utf-8');
  return home;
}

export async function runCodex(
  task: string,
  opts: {
    config: Config;
    /** Optional prior conversation inlined into the prompt. */
    history?: Array<{ role: 'user' | 'assistant'; content: string }>;
    onStdout?: (chunk: string) => void;
    onStderr?: (chunk: string) => void;
    signal?: AbortSignal;
  },
): Promise<CodexResult> {
  if (!opts.config.zenn_api_key) throw new Error('no ck_ key — sign in first');
  const home = await ensureCodexConfig(opts.config);

  // Inline history before the task so codex has full context.  It's a file-
  // editing agent so it'll read vault files for state, but prior turns still
  // matter for "continue with the same company" style follow-ups.
  const prelude =
    (opts.history ?? []).length === 0
      ? ''
      : '## Prior conversation\n\n' +
        opts.history!
          .map((h) => `**${h.role}:** ${h.content.trim()}`)
          .join('\n\n') +
        '\n\n## Current request\n\n';
  const prompt = prelude + task;

  const args = ['exec', '-C', VAULT_ROOT, '--skip-git-repo-check', '--full-auto', prompt];

  // Codex inherits env, and if the user has http_proxy / https_proxy set
  // for their normal browsing, codex will try to route localhost traffic
  // through it → 502. Scrub proxy vars and pin NO_PROXY to local hosts.
  const cleanEnv: NodeJS.ProcessEnv = { ...process.env };
  for (const k of ['HTTP_PROXY', 'HTTPS_PROXY', 'ALL_PROXY', 'http_proxy', 'https_proxy', 'all_proxy']) {
    delete cleanEnv[k];
  }
  const env: NodeJS.ProcessEnv = {
    ...cleanEnv,
    OPENAI_API_KEY: opts.config.zenn_api_key,
    CODEX_HOME: home,
    NO_PROXY: '127.0.0.1,localhost',
    no_proxy: '127.0.0.1,localhost',
  };

  const started = Date.now();
  let stdout = '';
  let stderr = '';

  return new Promise<CodexResult>((resolve, reject) => {
    let proc: ChildProcess;
    try {
      proc = spawn('codex', args, { env, stdio: ['ignore', 'pipe', 'pipe'] });
    } catch (err) {
      if ((err as NodeJS.ErrnoException).code === 'ENOENT') return reject(new CodexNotInstalled());
      return reject(err);
    }
    proc.on('error', (err) => {
      if ((err as NodeJS.ErrnoException).code === 'ENOENT') reject(new CodexNotInstalled());
      else reject(err);
    });
    proc.stdout?.setEncoding('utf-8');
    proc.stdout?.on('data', (chunk: string) => {
      stdout += chunk;
      opts.onStdout?.(chunk);
    });
    proc.stderr?.setEncoding('utf-8');
    proc.stderr?.on('data', (chunk: string) => {
      stderr += chunk;
      opts.onStderr?.(chunk);
    });
    opts.signal?.addEventListener('abort', () => {
      try { proc.kill('SIGTERM'); } catch {}
    });
    proc.on('exit', (code) => {
      resolve({ stdout, stderr, exitCode: code ?? -1, durationMs: Date.now() - started });
    });
  });
}

export async function codexAvailable(): Promise<boolean> {
  return new Promise((resolve) => {
    try {
      const proc = spawn('codex', ['--version'], { stdio: ['ignore', 'ignore', 'ignore'] });
      proc.on('error', () => resolve(false));
      proc.on('exit', (code) => resolve(code === 0));
    } catch {
      resolve(false);
    }
  });
}
