// Per-user integrations stored at ~/BlackMagic/.bm/integrations.json.
// Credentials stay local; we never upload them.

import fs from 'node:fs/promises';
import fsSync from 'node:fs';
import path from 'node:path';
import { getVaultRoot } from './paths.js';

export type IntegrationProvider =
  | 'hubspot'
  | 'attio'
  | 'salesforce'
  | 'gong'
  | 'unipile'
  | 'slack'
  | 'gmail'
  | 'feishu'
  | 'metabase'
  | 'supabase'
  | 'calcom'
  | 'discord'
  | 'telegram'
  | 'notion'
  | 'linear'
  | 'github'
  | 'stripe'
  | 'apify'
  | 'amazon_ses';

export const PROVIDERS: IntegrationProvider[] = [
  'hubspot', 'attio', 'salesforce', 'gong', 'unipile', 'slack', 'gmail',
  'feishu', 'metabase', 'supabase',
  'calcom', 'discord', 'telegram', 'notion', 'linear', 'github', 'stripe',
  'apify', 'amazon_ses',
];

export interface IntegrationRecord {
  status: 'connected' | 'disconnected';
  connectedAs?: string | null;
  connectedAt?: string | null;
  credentials?: Record<string, string>;  // never sent to the UI; daemon-internal
}

type Store = Partial<Record<IntegrationProvider, IntegrationRecord>>;

const FILE = () => path.join(getVaultRoot(), '.bm', 'integrations.json');
const ENV_FILE = () => path.join(getVaultRoot(), '.env');

async function load(): Promise<Store> {
  try {
    return JSON.parse(await fs.readFile(FILE(), 'utf-8')) as Store;
  } catch {
    return {};
  }
}

// Per-provider mapping from credential field → environment variable.
// Skills + scripts inside the vault `load_dotenv()` and reach for these
// names. Only BYOK (bring-your-own-key) integrations are mirrored here —
// LLM credits live in `config.toml` and never touch `.env`, so skills
// can't accidentally use the user's `ck_` token to bypass billing.
const ENV_MAPPING: Record<IntegrationProvider, Record<string, string>> = {
  apify:        { token: 'APIFY_API_TOKEN' },
  amazon_ses:   {
    access_key_id:     'AWS_ACCESS_KEY_ID',
    secret_access_key: 'AWS_SECRET_ACCESS_KEY',
    region:            'AWS_REGION',
    from:              'SES_FROM',
  },
  feishu:       { token: 'FEISHU_WEBHOOK', endpoint: 'FEISHU_WEBHOOK' },
  hubspot:      { token: 'HUBSPOT_API_KEY' },
  attio:        { token: 'ATTIO_API_KEY', endpoint: 'ATTIO_BASE_URL' },
  salesforce:   { token: 'SALESFORCE_ACCESS_TOKEN' },
  gong:         { token: 'GONG_ACCESS_KEY' },
  unipile:      { token: 'UNIPILE_API_KEY', endpoint: 'UNIPILE_BASE_URL' },
  slack:        { token: 'SLACK_BOT_TOKEN' },
  gmail:        { token: 'GMAIL_OAUTH_TOKEN' },
  metabase:     { token: 'METABASE_API_KEY', endpoint: 'METABASE_BASE_URL' },
  supabase:     { token: 'SUPABASE_SERVICE_ROLE_KEY', endpoint: 'SUPABASE_URL' },
  calcom:       { token: 'CALCOM_API_KEY' },
  discord:      { token: 'DISCORD_BOT_TOKEN', endpoint: 'DISCORD_WEBHOOK' },
  telegram:     { token: 'TELEGRAM_BOT_TOKEN' },
  notion:       { token: 'NOTION_API_KEY' },
  linear:       { token: 'LINEAR_API_KEY' },
  github:       { token: 'GITHUB_TOKEN' },
  stripe:       { token: 'STRIPE_RESTRICTED_KEY' },
};

const ENV_HEADER = `# AUTO-GENERATED by BlackMagic AI from .bm/integrations.json — do not edit by hand.
# This file mirrors your BYOK (bring-your-own-key) integrations as plain
# KEY=value pairs so skills + scripts can \`load_dotenv()\` them. LLM
# billing keys live in .bm/config.toml and are never written here.
`;

function escapeEnvValue(v: string): string {
  // Wrap in double quotes if value has whitespace/special chars; escape
  // backslashes and double quotes inside the quoted form.
  if (/^[A-Za-z0-9_./:@\-+=]+$/.test(v)) return v;
  return `"${v.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`;
}

async function writeEnvMirror(store: Store): Promise<void> {
  const lines: string[] = [ENV_HEADER];
  // Stable provider order = PROVIDERS array order, so diffs stay clean.
  for (const provider of PROVIDERS) {
    const rec = store[provider];
    const creds = rec?.credentials;
    if (!creds || rec.status !== 'connected') continue;
    const mapping = ENV_MAPPING[provider];
    if (!mapping) continue;
    const block: string[] = [];
    for (const [credField, envKey] of Object.entries(mapping)) {
      const v = creds[credField];
      if (!v) continue;
      block.push(`${envKey}=${escapeEnvValue(String(v))}`);
    }
    if (block.length > 0) {
      lines.push(`# ── ${provider} ─────────────────────────────────────────────`);
      lines.push(...block);
      lines.push('');
    }
  }
  await fs.mkdir(path.dirname(ENV_FILE()), { recursive: true });
  await fs.writeFile(ENV_FILE(), lines.join('\n'), 'utf-8');
}

async function save(store: Store): Promise<void> {
  await fs.mkdir(path.dirname(FILE()), { recursive: true });
  await fs.writeFile(FILE(), JSON.stringify(store, null, 2) + '\n', 'utf-8');
  await writeEnvMirror(store);
}

/** Re-emit the .env mirror from the current integrations.json. Called
 *  on daemon startup so users who upgrade past this version get their
 *  pre-existing integrations exposed via .env without having to
 *  re-paste anything. */
export async function regenerateEnvMirror(): Promise<void> {
  await writeEnvMirror(await load());
}

export async function listIntegrations() {
  const store = await load();
  return PROVIDERS.map((p) => {
    const r = store[p];
    return {
      provider: p,
      status: r?.status ?? 'disconnected',
      connectedAs: r?.connectedAs ?? null,
      connectedAt: r?.connectedAt ?? null,
    };
  });
}

export async function saveIntegration(
  provider: IntegrationProvider,
  credentials: Record<string, string>,
): Promise<void> {
  if (!PROVIDERS.includes(provider)) throw new Error(`unknown provider: ${provider}`);
  const store = await load();
  const connectedAs =
    credentials.email ?? credentials.workspace ?? credentials.account ?? null;
  store[provider] = {
    status: 'connected',
    connectedAs,
    connectedAt: new Date().toISOString(),
    credentials,
  };
  await save(store);
}

export async function deleteIntegration(provider: IntegrationProvider): Promise<void> {
  const store = await load();
  delete store[provider];
  await save(store);
}

export async function readCredentials(
  provider: IntegrationProvider,
): Promise<Record<string, string> | null> {
  const store = await load();
  return store[provider]?.credentials ?? null;
}

// OAuth start URLs. V1: each provider's native OAuth app URL with a
// redirect-back to the local daemon. For providers where we don't yet have
// a registered OAuth app, return a marker URL the renderer can show a
// "Paste token instead" hint for.
export function oauthStartUrl(
  provider: IntegrationProvider,
  daemonPort: number,
  localToken: string,
  billingUrl: string,
): { browserUrl: string; supported: boolean } {
  const returnUrl = `http://127.0.0.1:${daemonPort}/integrations/${provider}/callback?token=${encodeURIComponent(localToken)}`;
  // Blackmagic.run hosts the per-provider auth page; it'll bounce the user
  // into the real OAuth flow once apps are registered.
  const browserUrl = `${billingUrl.replace(/\/+$/, '')}/oauth/${provider}?return=${encodeURIComponent(returnUrl)}`;
  return { browserUrl, supported: true };
}
